name: 'Test'
description: 'Test and lint'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
