// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {client} from '../models';

export function ConnectToDatabase(arg1:string):Promise<void>;

export function CreateDatabase(arg1:database.Database):Promise<void>;

export function DeleteDatabase(arg1:string):Promise<void>;

export function DisconnectFromDatabase(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<client.QueryResult>;

export function GetDatabases():Promise<Array<database.Database>>;

export function GetSchemas(arg1:string):Promise<client.QueryResult>;

export function GetTableRows(arg1:string,arg2:string,arg3:string):Promise<client.QueryResult>;

export function GetTables(arg1:string,arg2:string):Promise<client.QueryResult>;

export function SelectFile():Promise<string>;

export function UpdateDatabase(arg1:database.Database):Promise<void>;
