// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function CreateConnection(arg1) {
  return window['go']['app']['App']['CreateConnection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['app']['App']['Disconnect'](arg1);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['app']['App']['ExecuteQuery'](arg1, arg2);
}

export function GetConnections() {
  return window['go']['app']['App']['GetConnections']();
}

export function GetSchemas(arg1) {
  return window['go']['app']['App']['GetSchemas'](arg1);
}

export function GetTableRows(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableRows'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['app']['App']['GetTables'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['app']['App']['SelectFile']();
}

export function UpdateConnection(arg1) {
  return window['go']['app']['App']['UpdateConnection'](arg1);
}
