// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToDatabase(arg1) {
  return window['go']['app']['App']['ConnectToDatabase'](arg1);
}

export function CreateDatabase(arg1) {
  return window['go']['app']['App']['CreateDatabase'](arg1);
}

export function DeleteDatabase(arg1) {
  return window['go']['app']['App']['DeleteDatabase'](arg1);
}

export function DisconnectFromDatabase(arg1) {
  return window['go']['app']['App']['DisconnectFromDatabase'](arg1);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['app']['App']['ExecuteQuery'](arg1, arg2);
}

export function GetDatabases() {
  return window['go']['app']['App']['GetDatabases']();
}

export function GetSchemas(arg1) {
  return window['go']['app']['App']['GetSchemas'](arg1);
}

export function GetTableRows(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableRows'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['app']['App']['GetTables'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['app']['App']['SelectFile']();
}

export function UpdateDatabase(arg1) {
  return window['go']['app']['App']['UpdateDatabase'](arg1);
}
