// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {client} from '../models';

export function Connect(arg1:string):Promise<void>;

export function CreateConnection(arg1:app.Connection):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<client.QueryResult>;

export function GetConnections():Promise<Array<app.Connection>>;

export function GetSchemas(arg1:string):Promise<client.QueryResult>;

export function GetTableRows(arg1:string,arg2:string,arg3:string):Promise<client.QueryResult>;

export function GetTables(arg1:string,arg2:string):Promise<client.QueryResult>;

export function SelectFile():Promise<string>;

export function UpdateConnection(arg1:app.Connection):Promise<void>;
