name: "Compress"
description: "Compress built files"
inputs:
  go-version:
    description: "Go version"
  node-version:
    description: "Node version"
runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      shell: bash
      working-directory: build/bin
      run: |
        zip -r dbisous-linux.zip *
    - if: runner.os == 'Windows'
      shell: pwsh
      working-directory: build/bin
      run: |
        Compress-Archive -Path * -Destination dbisous-windows.zip
    - if: runner.os == 'macOs'
      shell: bash
      working-directory: build/bin
      run: |
        zip -r dbisous-linux.zip *
