on:
  push:
    branches:
      - '*'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
  setup-node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
  build:
    runs-on: ubuntu-latest
    needs: [checkout, setup-go, setup-node]
    steps:
      - uses: ./.github/actions/build
  typecheck:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - shell: bash
        run: make typecheck
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - shell: bash
        run: make lint
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - shell: bash
        run: make test
