on:
  push:
    branches:
      - '*'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  setup:
    needs: checkout
    uses: ./.github/workflows/setup.yml
  install:
    needs: setup
    uses: ./.github/workflows/install.yml
  test:
    needs: install
    uses: ./.github/workflows/test.yml
