on:
  push:
    branches:
      - '*'

env:
  GO_VERSION: "1.24"
  NODE_VERSION: "22"

jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # checkout to get go.sum and enable caching
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
  setup-node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
  build:
    runs-on: ubuntu-latest
    needs: [setup-go, setup-node]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: ./.github/actions/build
      - uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
      - uses: actions/cache@v4
        with:
          path: frontend/wailsjs
          key: ${{ runner.os }}-wailsjs-${{ hashFiles('app/**') }}
      - uses: actions/cache@v4
        with:
          path: frontend/auto-imports.d.ts
          key: ${{ runner.os }}-wailsjs-${{ hashFiles('frontend/src/**') }}
  typecheck:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
      - shell: bash
        run: make typecheck
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
      - uses: actions/cache@v4
        with:
          path: frontend/wailsjs
          key: ${{ runner.os }}-wailsjs-${{ hashFiles('app/**') }}
      - uses: actions/cache@v4
        with:
          path: frontend/auto-imports.d.ts
          key: ${{ runner.os }}-wailsjs-${{ hashFiles('frontend/src/**') }}
      - shell: bash
        run: make lint
  # test:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps: 
  #     - shell: bash
  #       run: make test
