on:
  push:
    branches:
      - '*'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup.yml
      - uses: ./.github/workflows/test.yml
