on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        if: runner.os == 'Linux'
        run: |
          echo "/home/runner/go/bin" >> $PATH
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          echo $PATH
          echo $(go env GOPATH)
          wails build -tags webkit2_41
      - shell: pwsh
        if: runner.os == 'Windows'
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails build
      - shell: bash
        if: runner.os == 'macOS'
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails build -platform darwin/universal
