on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
            build/bin/
            build\bin\
      - uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            */bin/*
          fail_on_unmatched_files: true
