on:
  release:
    types: [published]

env:
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup.yml
      - uses: ./.github/workflows/build.yml
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            build/bin/*.zip
