on:
  push:
    tags:
      - '*'

env:
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            build/bin/*.zip
