on:
  workflow_call:
    inputs:
      go-version:
        type: string
      node-version:
        type: string

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # checkout to get go.sum and enable caching
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
  node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
