on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps: 
      - shell: bash
        run: sudo apt update
      - shell: bash
        run: sudo apt install libwebkit2gtk-4.1-dev
      - shell: bash
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - shell: bash
        run: wails build -tags webkit2_41
      - shell: bash
        run: make typecheck
      - shell: bash
        run: make lint
      - shell: bash
        run: make test
