on:
  workflow_call:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps: 
      - shell: bash
        run: make typecheck
  lint:
    runs-on: ubuntu-latest
    steps: 
      - shell: bash
        run: make lint
  test:
    runs-on: ubuntu-latest
    steps: 
      - shell: bash
        run: make test
